<?php
/**
 * Custom Fields
 *
 * @package SimpleMag
 * @since 	SimpleMag 1.1
**/


if(function_exists("register_field_group")){
	register_field_group(array (
		'id' => 'acf_category-options',
		'title' => 'Category Options',
		'fields' => array (
			array (
				'key' => 'field_516807bdd9f14',
				'label' => 'Latest Posts in drop down menu',
				'name' => 'menu_latest_posts',
				'type' => 'radio',
				'instructions' => 'Enable or Disable latest posts in the drop down menu of this category',
				'choices' => array (
					'latest_posts_on' => 'Enable',
					'latest_posts_off' => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'latest_posts_on',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_66',
				'label' => 'Category Slider',
				'name' => 'category_slider',
				'type' => 'radio',
				'instructions' => 'Enable or Disable this category slider',
				'choices' => array (
					'cat_slider_on' => 'Enable',
					'cat_slider_off' => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'cat_slider_off',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_51f544100ad21',
				'label' => 'Slider Position',
				'name' => 'category_slider_position',
				'type' => 'radio',
				'instructions' => 'Place the slider full width or above the content',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_66',
							'operator' => '==',
							'value' => 'cat_slider_on',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'cat_slider_full' => 'Full Width',
					'cat_slider_above' => 'Above The Content',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'cat_slider_full',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_51c6f934bf408',
				'label' => 'Category Sidebar',
				'name' => 'category_sidebar',
				'type' => 'radio',
				'instructions' => 'Enable or Disable the sidebar for this category',
				'choices' => array (
					'cat_sidebar_on' => 'Enable',
					'cat_sidebar_off' => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'cat_sidebar_on',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_51e2688e41429',
				'label' => 'Posts Layout',
				'name' => 'category_posts_layout',
				'type' => 'radio',
				'instructions' => 'Select posts layout for this category',
				'choices' => array (
					'masonry-layout' => 'Masonry',
					'classic-layout' => 'Classic Blog',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'classic-layout',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_format-audio',
		'title' => 'Format Audio',
		'fields' => array (
			array (
				'key' => 'field_51b01e1ec60a8',
				'label' => 'Add SoundCloud Audio',
				'name' => 'add_audio_url',
				'type' => 'text',
				'instructions' => 'Paste page URL from SoundCloud',
				'default_value' => '',
				'formatting' => 'none',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'audio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_format-gallery',
		'title' => 'Format Gallery',
		'fields' => array (
			array (
				'key' => 'field_51b01e988b9a1',
				'label' => 'Upload gallery image',
				'name' => 'post_upload_gallery',
				'type' => 'gallery',
				'preview_size' => 'thumbnail',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'gallery',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_format-video',
		'title' => 'Format Video',
		'fields' => array (
			array (
				'key' => 'field_55',
				'label' => 'Add Video',
				'name' => 'add_video_url',
				'type' => 'text',
				'instructions' => 'Paste video page URL',
				'default_value' => '',
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_format',
					'operator' => '==',
					'value' => 'video',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-composer',
		'title' => 'Page Composer',
		'fields' => array (
			array (
				'key' => 'field_36',
				'label' => 'Page Composer',
				'name' => 'page_composer',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Title/Text',
						'name' => 'title_or_text',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_51f4eff7a9184',
								'label' => 'Title/Text Styling',
								'name' => 'title_styling',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'theme_title' => 'Theme Title',
									'heading_1' => 'Heading 1',
									'heading_2' => 'Heading 2',
									'bold_text' => 'Bold',
									'paragraph_text' => 'Paragraph',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'theme_title',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51d0190ee3e96',
								'label' => 'Content',
								'name' => 'title_text_content',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
						),
					),
					array (
						'label' => 'Posts Slider',
						'name' => 'hp_posts_slider',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_37',
								'label' => 'Posts to show',
								'name' => 'slides_to_show',
								'type' => 'select',
								'instructions' => 'Select the maximum number of posts you want to show in the slider',
								'column_width' => '',
								'choices' => array (
									1 => 1,
									2 => 2,
									3 => 3,
									4 => 4,
									5 => 5,
									6 => 6,
									7 => 7,
									8 => 8,
									9 => 9,
									10 => 10,
								),
								'default_value' => 3,
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'Custom Slider',
						'name' => 'custom_slider',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_51dd76414cbc9',
								'label' => 'Slides',
								'name' => 'custom_add_new_slide',
								'type' => 'repeater',
								'instructions' => 'Leave Button Text empty if you don\'t want to show the button',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_51dd76584cbca',
										'label' => 'Slide Image',
										'name' => 'custom_slide_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'id',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_51dd76864cbcb',
										'label' => 'Slide Title',
										'name' => 'custom_slide_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'formatting' => 'none',
									),
									array (
										'key' => 'field_51dd76a64cbcc',
										'label' => 'Button Text',
										'name' => 'custom_button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'formatting' => 'none',
									),
									array (
										'key' => 'field_51dd76cf4cbcd',
										'label' => 'URL',
										'name' => 'custom_slide_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'formatting' => 'none',
									),
								),
								'row_min' => 1,
								'row_limit' => 10,
								'layout' => 'table',
								'button_label' => 'Add Slide',
							),
						),
					),
					array (
						'label' => 'Featured Posts',
						'name' => 'hp_featured_posts',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_39',
								'label' => 'Main Title',
								'name' => 'featured_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_40',
								'label' => 'Sub Title',
								'name' => 'featured_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_51a1ca6e05fe8',
								'label' => 'Posts Excerpt',
								'name' => 'featured_excerpt',
								'type' => 'radio',
								'instructions' => 'Choose to enable or disable the excerpt',
								'column_width' => '',
								'choices' => array (
									'enable' => 'Enable',
									'disable' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'enable',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51dfd9bdc84f7',
								'label' => 'Posts Per page',
								'name' => 'featured_posts_per_page',
								'type' => 'number',
								'instructions' => 'How many posts you want to show at once',
								'column_width' => '',
								'default_value' => 3,
								'min' => 2,
								'max' => '',
								'step' => 1,
							),
						),
					),
					array (
						'label' => 'Latest By Category',
						'name' => 'latest_by_category',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_41',
								'label' => 'Main Title',
								'name' => 'category_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_42',
								'label' => 'Sub Title',
								'name' => 'category_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_43',
								'label' => 'Category',
								'name' => 'category_section_name',
								'type' => 'taxonomy',
								'instructions' => 'Select the category for this section',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_51a1cddf5ec24',
								'label' => 'Posts Excerpt',
								'name' => 'category_excerpt',
								'type' => 'radio',
								'instructions' => 'Choose to enable or disable the excerpt',
								'column_width' => '',
								'choices' => array (
									'enable' => 'Enable',
									'disable' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'enable',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51de6d2b35ac0',
								'label' => 'Posts Per Page',
								'name' => 'category_posts_per_page',
								'type' => 'number',
								'instructions' => 'How many posts you want to show at once',
								'column_width' => '',
								'default_value' => 3,
								'min' => 2,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_51f61b6a10abe',
								'label' => 'Pagination',
								'name' => 'category_pagination',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'cat_pagination_on' => 'Enable',
									'cat_pagination_off' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'cat_pagination_off',
								'layout' => 'horizontal',
							),
						),
					),
					array (
						'label' => 'Latest By Format',
						'name' => 'latest_by_format',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_44',
								'label' => 'Main Title',
								'name' => 'format_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_45',
								'label' => 'Sub Title',
								'name' => 'format_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_49',
								'label' => 'Format',
								'name' => 'format_section_name',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'standard' => 'Standard',
									'video' => 'Video',
									'audio' => 'Audio',
									'gallery' => 'Gallery',
								),
								'default_value' => 'standard',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_51a1ce185ec25',
								'label' => 'Posts Excerpt',
								'name' => 'format_excerpt',
								'type' => 'radio',
								'instructions' => 'Choose to enable or disable the excerpt',
								'column_width' => '',
								'choices' => array (
									'enable' => 'Enable',
									'disable' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'enable',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51aa0082eceb9',
								'label' => 'Posts Per Page',
								'name' => 'format_posts_per_page',
								'type' => 'number',
								'instructions' => 'How many posts you want to show at once',
								'column_width' => '',
								'default_value' => 3,
								'min' => 2,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_51aa046aecebd',
								'label' => 'Pagination',
								'name' => 'format_pagination',
								'type' => 'radio',
								'instructions' => 'Enable or Disable the pagination',
								'column_width' => '',
								'choices' => array (
									'pagination_on' => 'Enable',
									'pagination_off' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'pagination_off',
								'layout' => 'horizontal',
							),
						),
					),
					array (
						'label' => 'Latest Reviews',
						'name' => 'latest_reviews',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_5195e20601871',
								'label' => 'Main Title',
								'name' => 'reviews_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_5195e20601872',
								'label' => 'Sub Title',
								'name' => 'reviews_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_51a1ce455ec26',
								'label' => 'Posts Excerpt',
								'name' => 'reviews_excerpt',
								'type' => 'radio',
								'instructions' => 'Choose to enable or disable the excerpt',
								'column_width' => '',
								'choices' => array (
									'enable' => 'Enable',
									'disable' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'enable',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51aa0133eceba',
								'label' => 'Posts Per Page',
								'name' => 'reviews_posts_per_page',
								'type' => 'number',
								'instructions' => 'How many posts you want to show at once',
								'column_width' => '',
								'default_value' => 3,
								'min' => 2,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_51aa049decebe',
								'label' => 'Pagination',
								'name' => 'reviews_pagination',
								'type' => 'radio',
								'instructions' => 'Enable or Disable the pagination',
								'column_width' => '',
								'choices' => array (
									'pagination_on' => 'Enable',
									'pagination_off' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'pagination_off',
								'layout' => 'horizontal',
							),
						),
					),
					array (
						'label' => 'Latest Posts',
						'name' => 'latest_posts',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_46',
								'label' => 'Main Title',
								'name' => 'latest_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_47',
								'label' => 'Sub Title',
								'name' => 'latest_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_48',
								'label' => 'Posts Per Page',
								'name' => 'latest_posts_per_page',
								'type' => 'number',
								'instructions' => 'How many posts you want to show per page',
								'column_width' => '',
								'default_value' => 3,
								'min' => 2,
								'max' => '',
								'step' => 1,
							),
							array (
								'key' => 'field_51e24ee79fc05',
								'label' => 'Posts Layout',
								'name' => 'latest_posts_layout',
								'type' => 'radio',
								'instructions' => 'Select this section posts layout',
								'column_width' => '',
								'choices' => array (
									'masonry-layout' => 'Masonry',
									'classic-layout' => 'Classic Blog',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'masonry-layout',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51a9c7286dd23',
								'label' => 'Pagination',
								'name' => 'latest_pagination',
								'type' => 'radio',
								'instructions' => 'Enable or Disable the pagination',
								'column_width' => '',
								'choices' => array (
									'pagination_on' => 'Enable',
									'pagination_off' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'pagination_on',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_70',
								'label' => 'Sidebar',
								'name' => 'latest_posts_sidebar',
								'type' => 'radio',
								'instructions' => 'Disable if you Enable Page Sidebar',
								'column_width' => '',
								'choices' => array (
									'sidebar_on' => 'Enable',
									'sidebar_off' => 'Disable',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'sidebar_off',
								'layout' => 'horizontal',
							),
						),
					),
					array (
						'label' => 'Static Image',
						'name' => 'image_advertising',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_51f3cf0b1adfd',
								'label' => 'Main Title',
								'name' => 'static_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_51f3cf301adfe',
								'label' => 'Sub Title',
								'name' => 'static_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_51f3c29a4acfa',
								'label' => 'Image Type',
								'name' => 'static_image_mode',
								'type' => 'radio',
								'column_width' => '',
								'choices' => array (
									'static_image_regular' => 'Regular Image',
									'static_image_banner' => 'Banner',
								),
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'static_image_regular',
								'layout' => 'horizontal',
							),
							array (
								'key' => 'field_51c6fa31eabcc',
								'label' => 'Image URL',
								'name' => 'ad_banner_url',
								'type' => 'text',
								'instructions' => 'Enter the image URL',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'html',
							),
							array (
								'key' => 'field_51c84c720068d',
								'label' => 'Image Link',
								'name' => 'ad_banner_link',
								'type' => 'text',
								'instructions' => 'Leave blank to output the image without link',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
						),
					),
					array (
						'label' => 'Code Box',
						'name' => 'code_advertising',
						'display' => 'row',
						'sub_fields' => array (
							array (
								'key' => 'field_51f3f179c86d7',
								'label' => 'Main Title',
								'name' => 'code_main_title',
								'type' => 'text',
								'instructions' => 'Enter the main title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_51f3f192c86d8',
								'label' => 'Sub Title',
								'name' => 'code_sub_title',
								'type' => 'text',
								'instructions' => 'Enter the sub title for this section',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'none',
							),
							array (
								'key' => 'field_51c96d4afb2d6',
								'label' => 'Source Code',
								'name' => 'ad_banner_code',
								'type' => 'textarea',
								'instructions' => 'Supports text, HTML tags, JS code and video embed code',
								'column_width' => '',
								'default_value' => '',
								'formatting' => 'html',
							),
						),
					),
				),
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-composer.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'featured_image',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-options',
		'title' => 'Page Options',
		'fields' => array (
			array (
				'key' => 'field_71',
				'label' => 'Page Sidebar',
				'name' => 'page_sidebar',
				'type' => 'radio',
				'instructions' => 'Enable or Disable sidebar on this page. Disable to use this page full width.',
				'choices' => array (
					'page_sidebar_on' => 'Enable',
					'page_sidebar_off' => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'page_sidebar_on',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-options',
		'title' => 'Post Options',
		'fields' => array (
			array (
				'key' => 'field_51de854f61278',
				'label' => 'Media Position',
				'name' => 'post_media_position',
				'type' => 'radio',
				'choices' => array (
					'media_full_width' => 'Full Width',
					'media_above_content' => 'Above The Content',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'media_full_width',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_51e7bfe79bd65',
				'label' => 'Post Sidebar',
				'name' => 'post_sidebar',
				'type' => 'radio',
				'choices' => array (
					'post_sidebar_on' => 'Enable',
					'post_sidebar_off' => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'post_sidebar_on',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_52',
				'label' => 'Homepage Slider',
				'name' => 'homepage_slider_add',
				'type' => 'true_false',
				'message' => 'Add this post to homepage slider',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53',
				'label' => 'Category Slider',
				'name' => 'category_slider_add',
				'type' => 'true_false',
				'message' => 'Add this post to category slider',
				'default_value' => 0,
			),
			array (
				'key' => 'field_54',
				'label' => 'Make Featured',
				'name' => 'featured_post_add',
				'type' => 'true_false',
				'message' => 'Make this post featured',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-score',
		'title' => 'Post Score',
		'fields' => array (
			array (
				'key' => 'field_51adce9bc729d',
				'label' => 'Enable Post Score',
				'name' => 'enable_rating',
				'type' => 'true_false',
				'message' => 'Turn On the Score feature',
				'default_value' => 0,
			),
			array (
				'key' => 'field_51ade0f48bd2a',
				'label' => 'Rating Note',
				'name' => 'rating_note',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_51adce9bc729d',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'formatting' => 'none',
			),
			array (
				'key' => 'field_51adb7a0b081f',
				'label' => 'Score',
				'name' => 'rating_module',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_51adce9bc729d',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_51add3bcc729e',
						'label' => 'Label',
						'name' => 'score_label',
						'type' => 'text',
						'column_width' => 60,
						'default_value' => '',
						'formatting' => 'none',
					),
					array (
						'key' => 'field_51adb7cbb0820',
						'label' => 'Score',
						'name' => 'score_number',
						'type' => 'select',
						'column_width' => 40,
						'choices' => array (
							1 => 1,
							2 => 2,
							3 => 3,
							4 => 4,
							5 => 5,
							6 => 6,
							7 => 7,
							8 => 8,
							9 => 9,
							10 => 10,
						),
						'default_value' => '1 : 1',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => 1,
				'row_limit' => 10,
				'layout' => 'table',
				'button_label' => 'Add Score Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

/* Add-Ons
 * USING PREMIUN ADD-ONS OUTSIDE THIS THEME IS NOT ALLOWED!!!
 */
function ti_register_fields(){
	include_once('add-ons/acf-gallery/gallery.php');
	include_once('add-ons/acf-repeater/repeater.php');
	include_once('add-ons/acf-flexible-content/flexible-content.php');
}
add_action('acf/register_fields', 'ti_register_fields'); 